---
title: "Einführung in R"
---

## Installation

Was man machen muss, um mit R arbeiten zu können, hängt davon ab, welches Betriebssystem auf dem Gerät installiert ist.

### Windows und MacOS

Auf Windows und MacOS müssen wir zwei Programme installieren: zum einen die R-Distribution (das heißt, das Paket, mit dem man R-Code ausführen kann), zum anderen eine Entwicklungsumgebung, in der wir unseren R-Code schreiben können und die uns zahlreiche Hilfsmittel zum Schreiben unseres Codes und zum Anzeigen unserer Ergebnisse bietet.

1.  **R-Distribution**

    R ist eine frei verfügbare Software und kann somit von jedem kostenlos heruntergeladen werden.

    Ihr könnt sie installieren, indem ihr die Seite [cran.r-project.org](https://cran.r-project.org) aufruft und dort auf den Link *Download R for MacOS* bzw. *Download R for Windows* klickt. Wenn ihr ein MacBook habt, wählt ihr auf dieser Seite die passende Version für euer Gerät aus. Bei Windows klicken wir auf *base* und dann auf den Downloadlink ganz oben.

    Ihr folgt dann den Installationsanweisungen, dabei könnt ihr alles bei den Standardeinstellungen belassen.

2.  **Entwicklungsumgebung**

    Damit wir die R-Distribution sinnvoll nutzen können, benötigen wir eine Entwicklungsumgebung. In den vergangenen Jahren habe ich einige verschiedene ausprobiert, aber ich bin am Ende immer zu der bekanntesten Software für R zurückgekehrt, nämlich *RStudio Desktop*. RStudio ist eine von der Firma Posit entwickelte grafische Oberfläche, mit der ihr euren R-Code strukturiert schreiben und die Ergebnisse eurer Analyse ansprechend aufbereiten könnt. Natürlich könnt ihr auch andere Programme ausprobieren und benutzen, aber die weiteren Erklärungen sind auf RStudio ausgerichtet.

    Um RStudio zu installieren, geht auf die Seite [posit.co/download/rstudio-desktop](https://posit.co/download/rstudio-desktop). Dort seht ihr den Punkt *2:* *Install RStudio*. Es sollte bereits das richtige Betriebssystem vorgewählt sein, ansonsten finden sich darunter noch weitere Installer. Ladet nun durch Klick auf den Button *Download RStudio for ...* das Installationsprogramm herunter und folgt den Installationsanweisungen.

Nun sollten sowohl R als auch RStudio auf eurem Gerät installiert sein.

## iPads and Android tablets

*Under construction.*
